/**
 * Environment variables that must never be committed: they are either
 * generated by the local Zitadel bootstrap (and change every deployment run)
 * or issued by an external OIDC provider per-deployment. They live in the
 * gitignored `<env-file>.local` sibling of each committed env file, applied on
 * top of it (local wins).
 *
 * Single source of truth for the setup wizard and the test harness's env
 * layering. Shell scripts (`start-deployment.sh`, `run-api-tests.sh`) reference
 * this list by name in comments, since they cannot import it.
 */
export const LOCAL_ONLY_ENV_KEYS = [
  'OIDC_CLIENT_ID',
  'OIDC_CLIENT_SECRET',
  'TEST_CLIENT_ID',
  'TEST_CLIENT_SECRET',
] as const;

/** A key that belongs in the gitignored `.local` override, not the committed base file. */
export type LocalOnlyEnvKey = (typeof LOCAL_ONLY_ENV_KEYS)[number];

/** True when `key` is one of the {@link LOCAL_ONLY_ENV_KEYS}. */
export function isLocalOnlyEnvKey(key: string): key is LocalOnlyEnvKey {
  return (LOCAL_ONLY_ENV_KEYS as readonly string[]).includes(key);
}
