/**
 * The values `docker/nginx/10-tcp-init.sh` writes into `/config.js` at
 * container start (ADR-029). Two values, both about identity — the API
 * address is absent by construction, since the app always calls `/api` on
 * its own origin.
 */
export interface RuntimeConfig {
  oidcIssuerUrl: string;
  oidcClientId: string;
  /**
   * Whether to read `profile` and `email` from the provider's userinfo
   * endpoint rather than the ID token (ADR-024). Optional, and absent means
   * `false`: Zitadel puts both claims in the ID token, and a provider that
   * does not is the exception this exists for.
   *
   * Emitted as an unquoted JavaScript boolean, which is the whole reason
   * `10-tcp-init.sh` normalises it rather than interpolating it as the other
   * two are — the string `'false'` would satisfy this type and be truthy.
   */
  oidcLoadUserInfo?: boolean;
  /**
   * The object-store console's origin (`MINIO_CONSOLE_URL`), for the archive
   * tray's Silo links. Optional: with either this or {@link storageBucket}
   * absent, the archive tray shows completed tasks as plain text instead of
   * links. Validated as an `http:`/`https:` URL by {@link getRuntimeConfig}
   * — it reaches an `href` unchecked otherwise, and `javascript:` or any
   * other scheme there is a trust boundary, not a typo to shrug off.
   */
  storageConsoleUrl?: string;
  /** The object store's bucket prefix (`MINIO_BUCKET_PREFIX`), e.g. `tcp`. */
  storageBucket?: string;
}

declare global {
  interface Window {
    /**
     * Set by the inline assignment in `/config.js`, loaded via a plain
     * `<script>` tag in `index.html` ahead of the bundle. Optional because
     * that script is generated by the nginx container and is absent under a
     * bare `vite dev` — see {@link getRuntimeConfig} for what that produces.
     */
    __TCP_CONFIG__?: RuntimeConfig;
  }
}

/**
 * Reads the runtime configuration nginx generated for this environment.
 *
 * Throws rather than falling back to a default: a silent fallback would
 * quietly point the app at the wrong identity provider, which is exactly the
 * "which environment am I pointed at?" confusion `config.js`'s `no-store`
 * cache header exists to prevent. Not memoised — reading a global is not
 * expensive, and there is nothing to invalidate.
 */
export const getRuntimeConfig = (): RuntimeConfig => {
  const config = window.__TCP_CONFIG__;
  if (!config || !config.oidcIssuerUrl || !config.oidcClientId) {
    throw new Error(
      'Runtime configuration is missing or incomplete. The app reads ' +
        'window.__TCP_CONFIG__, which is set by /config.js — generated by ' +
        'the nginx container at startup (docker/nginx/10-tcp-init.sh), not ' +
        'part of the build.\n\n' +
        'The usual cause is running `vite dev` directly: there is no nginx ' +
        'in front of it, so /config.js 404s and window.__TCP_CONFIG__ is ' +
        'never set.\n\n' +
        'Fix: run the stack with `scripts/start-deployment.sh --dev-web` ' +
        'and load the nginx port (EXPOSE_PORT_WEB), not the Vite port.',
    );
  }
  return { ...config, storageConsoleUrl: validatedStorageConsoleUrl(config) };
};

/**
 * `storageConsoleUrl` reaches an `href` unchecked (`ArchiveDetails`), so a
 * non-`http:`/`https:` value — `javascript:`, `data:`, anything else — is
 * dropped rather than trusted. This is the one runtime-config field that
 * isn't merely malformed-or-not: a bad scheme here is a live injection
 * vector, not a typo, so it's silently ignored (falls back to the
 * plain-text archive tray) rather than failing the whole app the way a
 * missing `oidcIssuerUrl` does.
 */
const validatedStorageConsoleUrl = (
  config: RuntimeConfig,
): string | undefined => {
  const value = config.storageConsoleUrl;
  if (value === undefined) {
    return undefined;
  }
  try {
    const url = new URL(value);
    return url.protocol === 'http:' || url.protocol === 'https:'
      ? value
      : undefined;
  } catch {
    return undefined;
  }
};
