import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { WizardConfig } from '../types';

const REPO_ROOT = join(__dirname, '..', '..', '..');

/**
 * Writes a `.env.<instance>` file with explanatory comments. If the file
 * already exists, preserves values the user has manually edited — only
 * variables absent from the existing file are written.
 */
export function writeEnvFile(config: WizardConfig): string {
  const filePath = join(REPO_ROOT, config.envFileName);
  const existing = existsSync(filePath)
    ? parseExistingEnv(filePath)
    : new Map<string, string>();

  const lines: string[] = [];
  lines.push(`# LCP Server — ${config.instanceName} environment`);
  lines.push(`# Generated by setup wizard. Edit freely; re-running the wizard`);
  lines.push(`# preserves values you have changed.\n`);

  // --- Database ---
  lines.push('# PostgreSQL');
  writeVar(lines, existing, 'DATABASE_URL', 'postgres://lcp:dev-password@localhost:5432/lcp');
  lines.push('');

  // --- Redis ---
  lines.push('# Redis');
  writeVar(lines, existing, 'REDIS_URL', 'redis://localhost:6379');
  lines.push('');

  // --- MinIO ---
  lines.push('# MinIO object storage');
  writeVar(lines, existing, 'MINIO_ENDPOINT', 'http://localhost:9000');
  writeVar(lines, existing, 'MINIO_ACCESS_KEY', 'lcp-access-key');
  writeVar(lines, existing, 'MINIO_SECRET_KEY', 'lcp-secret-key');
  writeVar(lines, existing, 'MINIO_BUCKET_PREFIX', 'lcp');
  lines.push('');

  // --- OIDC ---
  if (config.oidc) {
    lines.push('# OpenID Connect authentication');
    writeVar(lines, existing, 'OIDC_ISSUER_URL', config.oidc.issuerUrl);
    writeVar(lines, existing, 'OIDC_CLIENT_ID', config.oidc.clientId);
    writeVar(lines, existing, 'OIDC_CLIENT_SECRET', config.oidc.clientSecret);
  } else {
    lines.push('# OpenID Connect — stubbed for local development');
    lines.push('# OIDC_ISSUER_URL=http://localhost:8080');
    lines.push('# OIDC_CLIENT_ID=');
    lines.push('# OIDC_CLIENT_SECRET=');
  }
  lines.push('');

  // --- Internal auth ---
  lines.push('# Internal service-to-service authentication');
  writeVar(lines, existing, 'INTERNAL_API_KEY', 'change-me-in-production');
  lines.push('');

  // --- LLM (inference) ---
  if (config.inferenceModel) {
    lines.push('# LLM inference (chat completions)');
    writeVar(lines, existing, 'LLM_PROVIDER', config.inferenceModel.provider);
    writeVar(lines, existing, 'LLM_MODEL', config.inferenceModel.model);
    writeVar(lines, existing, 'LLM_BASE_URL', config.inferenceModel.baseUrl);
    writeVar(lines, existing, 'LLM_API_KEY', config.inferenceModel.apiKey);
    if (config.inferenceModel.contextWindow) {
      writeVar(lines, existing, 'LLM_CONTEXT_WINDOW', String(config.inferenceModel.contextWindow));
    }
  } else {
    lines.push('# LLM inference — not configured (set per-role or per-company)');
    lines.push('# LLM_PROVIDER=');
    lines.push('# LLM_MODEL=');
    lines.push('# LLM_BASE_URL=');
    lines.push('# LLM_API_KEY=');
  }
  lines.push('');

  // --- Embedding ---
  if (config.embeddingModel) {
    lines.push('# Embedding model');
    writeVar(lines, existing, 'EMBEDDING_PROVIDER', config.embeddingModel.provider);
    writeVar(lines, existing, 'EMBEDDING_MODEL', config.embeddingModel.model);
    writeVar(lines, existing, 'EMBEDDING_BASE_URL', config.embeddingModel.baseUrl);
    writeVar(lines, existing, 'EMBEDDING_API_KEY', config.embeddingModel.apiKey);
    const dim = config.embeddingModel.dimension ?? 768;
    writeVar(lines, existing, 'EMBEDDING_DIMENSION', String(dim));
  } else {
    lines.push('# Embedding model — not configured (set per-company)');
    lines.push('# EMBEDDING_PROVIDER=');
    lines.push('# EMBEDDING_MODEL=');
    lines.push('# EMBEDDING_BASE_URL=');
    lines.push('# EMBEDDING_API_KEY=');
    writeVar(lines, existing, 'EMBEDDING_DIMENSION', '768');
  }
  lines.push('');

  // --- Agent limits ---
  lines.push('# Agent resource limits');
  writeVar(lines, existing, 'AGENT_ITERATIONS', String(config.agentIterations));
  writeVar(lines, existing, 'AGENT_WORKER_CONCURRENCY', String(config.agentConcurrency));
  lines.push('');

  // --- Misc ---
  lines.push('# Miscellaneous');
  writeVar(lines, existing, 'LCP_MASK_API_KEYS', 'true');
  writeVar(lines, existing, 'KNOWLEDGE_POLL_INTERVAL_MS', '60000');
  lines.push('');

  const content = lines.join('\n');
  writeFileSync(filePath, content, 'utf8');
  return filePath;
}

/**
 * Reads an existing env file into an ordered map, preserving comments and
 * blank lines so we can detect which variables the user has set.
 */
function parseExistingEnv(filePath: string): Map<string, string> {
  const content = readFileSync(filePath, 'utf8');
  const result = new Map<string, string>();
  for (const raw of content.split('\n')) {
    const line = raw.trim();
    if (line.length === 0 || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    result.set(line.slice(0, eq).trim(), line.slice(eq + 1).trim());
  }
  return result;
}

/**
 * Writes a `KEY=value` line. If the variable already exists in the env file,
 * preserves the user's value instead of overwriting.
 */
function writeVar(
  lines: string[],
  existing: Map<string, string>,
  key: string,
  defaultValue: string,
): void {
  const value = existing.get(key) ?? defaultValue;
  lines.push(`${key}=${value}`);
}
