import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { LlmProviderConfig, WizardConfig } from '../types';
import {
  DEFAULT_DB_USER,
  DEFAULT_DB_PASSWORD,
  DEFAULT_DB_NAME,
  DEFAULT_MINIO_ACCESS_KEY,
  DEFAULT_MINIO_SECRET_KEY,
  DEFAULT_MINIO_BUCKET_PREFIX,
  DEFAULT_INTERNAL_API_KEY,
  DEFAULT_EMBEDDING_DIMENSION,
  DEFAULT_KNOWLEDGE_POLL_INTERVAL_MS,
  DEFAULT_TCP_MASK_API_KEYS,
  LOCAL_ONLY_ENV_KEYS,
} from '../utils/app-defaults';

const REPO_ROOT = join(__dirname, '..', '..', '..');

/** Paths written by {@link writeEnvFile}. */
export interface WrittenEnvFiles {
  /** The committed base env file (non-secret config). */
  envFile: string;
  /** The gitignored `<env-file>.local` override (generated/provider secrets). */
  localFile: string;
}

/**
 * Accumulates env-file lines, preserving any value the user already set for a
 * key (so re-running the wizard never clobbers manual edits). Every configured
 * value is written uncommented — optional-and-unset settings are emitted as
 * explicit comment blocks instead.
 */
function envBuilder(existing: Map<string, string>) {
  const lines: string[] = [];
  return {
    comment: (text: string): void => void lines.push(`# ${text}`),
    blank: (): void => void lines.push(''),
    /** Writes `KEY=value`, keeping an existing user value over `value`. */
    set: (key: string, value: string): void =>
      void lines.push(`${key}=${existing.get(key) ?? value}`),
    render: (): string => `${lines.join('\n')}\n`,
  };
}

/**
 * Writes a committed `.env.<instance>` file (non-secret config) plus its
 * gitignored `.env.<instance>.local` sibling (the {@link LOCAL_ONLY_ENV_KEYS}
 * — OIDC/test client credentials). Client secrets never go in the committed
 * file. Existing values the user (or the Zitadel bootstrap) has written are
 * preserved in both files.
 */
export function writeEnvFile(
  config: WizardConfig,
  outputDir: string = REPO_ROOT,
): WrittenEnvFiles {
  const filePath = join(outputDir, config.envFileName);
  const localFilePath = `${filePath}.local`;
  const localFileName = `${config.envFileName}.local`;

  const b = envBuilder(readExistingEnv(filePath));

  b.comment(`TCP Server — ${config.instanceName} environment`);
  b.comment('Generated by setup wizard. Edit freely; re-running the wizard');
  b.comment('preserves values you have changed.');
  b.blank();

  b.comment('Database');
  b.set('DB_USER', DEFAULT_DB_USER);
  b.set('DB_PASSWORD', DEFAULT_DB_PASSWORD);
  b.set('DB_NAME', DEFAULT_DB_NAME);
  b.blank();

  b.comment(
    'Host ports. Each is independent; change one if something else uses it.',
  );
  b.comment('The bundled Zitadel always uses 8080 (not configurable).');
  b.set('EXPOSE_PORT_API', String(config.ports.api));
  b.set('EXPOSE_PORT_DB', String(config.ports.db));
  b.set('EXPOSE_PORT_MINIO', String(config.ports.minio));
  b.set('EXPOSE_PORT_MINIO_CONSOLE', String(config.ports.minioConsole));
  b.set('EXPOSE_PORT_WEB', String(config.ports.web));
  b.comment(
    'tcp-agent, published only with --dev-ports (start-dev.sh passes it).',
  );
  b.set('EXPOSE_PORT_AGENT', String(config.ports.agent));
  b.blank();

  b.comment('MinIO object storage');
  b.set('MINIO_ACCESS_KEY', DEFAULT_MINIO_ACCESS_KEY);
  b.set('MINIO_SECRET_KEY', DEFAULT_MINIO_SECRET_KEY);
  b.set('MINIO_BUCKET_PREFIX', DEFAULT_MINIO_BUCKET_PREFIX);
  b.blank();

  // Only the non-secret issuer URL is committed; client credentials live in the
  // gitignored `.local` override (written by buildLocalFile / the bootstrap).
  if (config.oidc) {
    b.comment('OpenID Connect authentication (external provider)');
    b.set('OIDC_ISSUER_URL', config.oidc.issuerUrl);
    b.comment(`OIDC_CLIENT_ID / OIDC_CLIENT_SECRET live in ${localFileName}`);
  } else {
    b.comment(
      'OpenID Connect — using the bundled Zitadel; issuer derived from',
    );
    b.comment('the Zitadel port. start-dev.sh bootstraps Zitadel and writes');
    b.comment(`OIDC_CLIENT_ID / OIDC_CLIENT_SECRET to ${localFileName}.`);
    b.comment('OIDC_ISSUER_URL=  # set only to point at an external provider');
  }
  b.blank();

  b.comment('Internal service-to-service authentication');
  b.set('INTERNAL_API_KEY', DEFAULT_INTERNAL_API_KEY);
  b.blank();

  if (config.stubLlm) {
    b.comment('Stub LLM — canned replies from docker/stub-llm/dev.jsonc');
    b.set('STUB_LLM', 'true');
    b.set('STUB_LLM_CONFIG_FILE', '/config/dev.jsonc');
    b.blank();
  }

  writeModelSection(
    b,
    'LLM inference (chat completions)',
    'LLM',
    config.inferenceModel ?? (config.stubLlm ? STUB_LLM_MODEL : undefined),
    'set per-role or per-company',
  );
  writeModelSection(
    b,
    'Embedding model',
    'EMBEDDING',
    config.embeddingModel,
    'set per-company',
  );

  b.comment('Agent resource limits');
  b.set('AGENT_ITERATIONS', String(config.agentIterations));
  b.set('AGENT_WORKER_CONCURRENCY', String(config.agentConcurrency));
  b.blank();

  b.comment('Miscellaneous');
  b.set('TCP_MASK_API_KEYS', String(DEFAULT_TCP_MASK_API_KEYS));
  b.set(
    'KNOWLEDGE_POLL_INTERVAL_MS',
    String(DEFAULT_KNOWLEDGE_POLL_INTERVAL_MS),
  );
  b.blank();

  // Read before the base file is rewritten: a Zitadel secret kept there (as
  // .env.example does) moves to .local instead of being dropped and replaced.
  const existingLocal = readExistingSecrets(filePath);
  writeFileSync(filePath, b.render(), 'utf8');
  writeFileSync(localFilePath, buildLocalFile(config, existingLocal), 'utf8');
  return { envFile: filePath, localFile: localFilePath };
}

/** The default LLM when the stub runs and no real model was configured. */
const STUB_LLM_MODEL: LlmProviderConfig = {
  provider: 'lm-studio', // any OpenAI-compatible server
  model: 'stub',
  baseUrl: 'http://stub-llm:3002/v1', // in-network: the agents call it
  apiKey: 'stub',
};

/**
 * Writes an LLM/embedding provider block: the collected `<PREFIX>_*` vars when a
 * model was configured, or a "not configured" note plus commented placeholders
 * otherwise. `EMBEDDING_DIMENSION` is always emitted so the schema is explicit.
 */
function writeModelSection(
  b: ReturnType<typeof envBuilder>,
  heading: string,
  prefix: 'LLM' | 'EMBEDDING',
  model: WizardConfig['inferenceModel'],
  note: string,
): void {
  if (model) {
    b.comment(heading);
    b.set(`${prefix}_PROVIDER`, model.provider);
    b.set(`${prefix}_MODEL`, model.model);
    b.set(`${prefix}_BASE_URL`, model.baseUrl);
    b.set(`${prefix}_API_KEY`, model.apiKey);
    if (prefix === 'LLM' && model.contextWindow) {
      b.set('LLM_CONTEXT_WINDOW', String(model.contextWindow));
    }
    if (prefix === 'EMBEDDING') {
      b.set(
        'EMBEDDING_DIMENSION',
        String(model.dimension ?? DEFAULT_EMBEDDING_DIMENSION),
      );
    }
  } else {
    b.comment(`${heading} — not configured (${note})`);
    for (const suffix of ['PROVIDER', 'MODEL', 'BASE_URL', 'API_KEY']) {
      b.comment(`${prefix}_${suffix}=`);
    }
    if (prefix === 'EMBEDDING') {
      b.set('EMBEDDING_DIMENSION', String(DEFAULT_EMBEDDING_DIMENSION));
    }
  }
  b.blank();
}

/**
 * Secrets the bundled Zitadel needs before it can start — without
 * `ZITADEL_ADMIN_PASSWORD`, start-deployment.sh leaves the auth profile off.
 * Generated once; a re-run keeps them, because a new masterkey would lock
 * Zitadel out of the data it already encrypted.
 */
const ZITADEL_SECRET_KEYS = [
  'ZITADEL_MASTERKEY',
  'ZITADEL_ADMIN_PASSWORD',
  'TEST_PASSWORD',
] as const;

/** A password meeting Zitadel's default policy (upper, lower, digit, symbol). */
function generatePassword(): string {
  return `${randomBytes(12).toString('base64url')}Aa1!`;
}

/**
 * Builds the gitignored `.local` override holding the {@link LOCAL_ONLY_ENV_KEYS}.
 * For an external OIDC provider the user-supplied client credentials are
 * written here; for the bundled Zitadel they are left for the bootstrap to
 * fill. Any values already present (e.g. from a previous bootstrap) are kept.
 */
function buildLocalFile(
  config: WizardConfig,
  existingLocal: Map<string, string>,
): string {
  const values = new Map(existingLocal);
  if (config.oidc) {
    values.set('OIDC_CLIENT_ID', config.oidc.clientId);
    values.set('OIDC_CLIENT_SECRET', config.oidc.clientSecret);
  }
  const zitadelKeys = config.oidc ? [] : ZITADEL_SECRET_KEYS;
  for (const key of zitadelKeys) {
    if (values.get(key)) continue;
    values.set(
      key,
      key === 'ZITADEL_MASTERKEY'
        ? randomBytes(16).toString('hex') // Zitadel needs exactly 32 chars
        : generatePassword(),
    );
  }

  const lines = [
    `# TCP Server — ${config.instanceName} local secret overrides (gitignored).`,
    '# Generated by the Zitadel bootstrap (start-dev.sh / start-deployment.sh),',
    '# or supplied here for an external OIDC provider. Never commit this file.',
    '',
  ];
  if (zitadelKeys.length > 0) {
    lines.push('# Bundled Zitadel — generated by the setup wizard.');
    for (const key of zitadelKeys) lines.push(`${key}=${values.get(key)}`);
    lines.push('');
  }
  const present = LOCAL_ONLY_ENV_KEYS.filter((key) => values.get(key));
  for (const key of present) lines.push(`${key}=${values.get(key)}`);
  if (present.length === 0) {
    lines.push(
      '# (Populated on the first start-dev.sh run by the Zitadel bootstrap.)',
    );
  }
  // Anything else already here (e.g. the bootstrap's TCP_ADMIN_IDENTIFIERS)
  // survives a re-run.
  const written = new Set<string>([...zitadelKeys, ...present]);
  for (const [key, value] of values) {
    if (!written.has(key) && value) lines.push(`${key}=${value}`);
  }
  return `${lines.join('\n')}\n`;
}

/**
 * The `.local` file's values, plus any {@link ZITADEL_SECRET_KEYS} found only
 * in the base env file. `.local` wins, as it does when the stack starts.
 */
function readExistingSecrets(envFilePath: string): Map<string, string> {
  const base = readExistingEnv(envFilePath);
  const values = readExistingEnv(`${envFilePath}.local`);
  for (const key of ZITADEL_SECRET_KEYS) {
    const value = base.get(key);
    if (value && !values.get(key)) values.set(key, value);
  }
  return values;
}

/**
 * Whether {@link writeEnvFile} would generate a new `ZITADEL_MASTERKEY` for
 * this config — the bundled Zitadel is in use and neither env file has one.
 * A new key can't decrypt a Zitadel database made with the old one.
 */
export function willGenerateMasterkey(
  config: WizardConfig,
  outputDir: string = REPO_ROOT,
): boolean {
  if (config.oidc) return false;
  const existing = readExistingSecrets(join(outputDir, config.envFileName));
  return !existing.get('ZITADEL_MASTERKEY');
}

/**
 * Reads an existing env file into a `KEY → value` map (comments and blanks
 * skipped), or an empty map when the file doesn't exist. Used to preserve
 * values the user or bootstrap has already written across a re-run.
 */
function readExistingEnv(filePath: string): Map<string, string> {
  const result = new Map<string, string>();
  if (!existsSync(filePath)) return result;
  for (const raw of readFileSync(filePath, 'utf8').split('\n')) {
    const line = raw.trim();
    if (line.length === 0 || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    result.set(line.slice(0, eq).trim(), line.slice(eq + 1).trim());
  }
  return result;
}
