#!/usr/bin/env bash
# Regenerates docs/licenses.md from the workspace manifests.
#
# license-report takes one --package per run, and the repo has two workspaces
# with production dependencies, so this emits a section per workspace rather
# than a single table. @tcp/shared is excluded from both: it is a local
# workspace package, not a third-party licence.
#
# Never edit docs/licenses.md by hand — it is regenerated by `npm run build`
# and by the pre-commit hook.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

report() {
  npx --no-install license-report \
    --config=.license-report.json \
    --output=markdown \
    --only=prod \
    --package="$1" \
    --exclude=@tcp/shared
}

{
  echo "## Backend"
  echo
  report apps/backend/package.json
  echo
  echo
  echo "## Web client"
  echo
  report apps/frontend/tcp-frontend/package.json
  echo
} > docs/licenses.md
