#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<EOF
Usage: $(basename "$0") [-h|--help] [--base-url URL] [-- <playwright options>]

Run the browser test suite against a running TCP web deployment.

Like the api and smoke tiers, this is a black-box client: it drives whatever is
serving at --base-url and provisions nothing itself (ADR-016). The deployment's
tcp-web service serves the app, so start a stack first:

  ./scripts/start-deployment.sh --project tcp-dev --env-file .env.dev
  $(basename "$0")

The URL is https, not http. The web service is TLS-only because HTTP/2 is a
requirement (ADR-025) and no browser negotiates HTTP/2 over cleartext. The
container's certificate is self-signed unless you mount your own, so Playwright
is configured to accept it — see docs/web-client.md for the mkcert route.

Point it at another stack with --base-url, for example the testing project on
EXPOSE_PORT_WEB=5174:

  $(basename "$0") --base-url https://localhost:5174

Browser binaries are large and are NOT installed by 'npm ci' — contributors who
never run this script never download them. This script installs Chromium on
first use.

Some specs (event-streams.spec.ts) need an authenticated machine token, the
same client_credentials grant the api tier uses. If --client-id/--client-secret
aren't given and TEST_CLIENT_ID/TEST_CLIENT_SECRET aren't already set, this
script reads them from the env file: --env-file if given, else .env.dev if
present, else .env.testing — checking its gitignored "<env-file>.local"
override first, since that's where start-deployment.sh writes the generated
values. Specs that need credentials skip themselves with a clear reason when
none are found; a missing token never fails the rest of the suite.

Any extra arguments after -- are passed through to Playwright, for example:
  $(basename "$0") -- --headed
  $(basename "$0") -- --grep "heading"

Options:
  --base-url URL             Web app base URL (default: https://localhost:\${EXPOSE_PORT_WEB:-5173})
  --oidc-discovery-url URL   Full OIDC discovery URL
                             (default: http://localhost:8080/.well-known/openid-configuration)
  --client-id ID             Machine test user client ID (client_credentials)
  --client-secret SECRET     Machine test user client secret
  --env-file PATH            Env file to read TEST_CLIENT_ID/SECRET from when
                             not otherwise provided (default: .env.dev, else .env.testing)
  -h, --help                 Show this help message and exit

--base-url can also be supplied as TCP_WEB_URL; the flag takes precedence.
EOF
}

BASE_URL="${TCP_WEB_URL:-https://localhost:${EXPOSE_PORT_WEB:-5173}}"
OIDC_URL=""
CLIENT_ID=""
CLIENT_SECRET=""
ENV_FILE=""
PASSTHROUGH=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-url)            BASE_URL="$2";       shift 2 ;;
    --oidc-discovery-url)  OIDC_URL="$2";       shift 2 ;;
    --client-id)           CLIENT_ID="$2";      shift 2 ;;
    --client-secret)       CLIENT_SECRET="$2";  shift 2 ;;
    --env-file)            ENV_FILE="$2";       shift 2 ;;
    --) shift; PASSTHROUGH+=("$@"); break ;;
    -h|--help) usage; exit 0 ;;
    *) PASSTHROUGH+=("$1"); shift ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND="$REPO_ROOT/apps/frontend/tcp-frontend"

# Resolve credentials from env file when not provided via CLI/env.
if [[ -z "$CLIENT_ID" || -z "$CLIENT_SECRET" ]]; then
  if [[ -z "$ENV_FILE" ]]; then
    if [[ -f "$REPO_ROOT/.env.dev" ]]; then
      ENV_FILE="$REPO_ROOT/.env.dev"
    else
      ENV_FILE="$REPO_ROOT/.env.testing"
    fi
  fi
  # TEST_CLIENT_ID/SECRET are generated by the Zitadel bootstrap, which writes
  # them to the gitignored "<env-file>.local" override (see start-deployment.sh),
  # not the committed base file. Prefer the override, fall back to the base file.
  for candidate in "$ENV_FILE.local" "$ENV_FILE"; do
    [[ -f "$candidate" ]] || continue
    [[ -n "$CLIENT_ID" ]]     || CLIENT_ID="$(grep -m1 '^TEST_CLIENT_ID=' "$candidate" | cut -d= -f2-)"
    [[ -n "$CLIENT_SECRET" ]] || CLIENT_SECRET="$(grep -m1 '^TEST_CLIENT_SECRET=' "$candidate" | cut -d= -f2-)"
  done
fi

# Playwright is a no-op if the browser is already present, so this is cheap on
# every run after the first. --with-deps needs root on Linux and is a no-op on
# macOS, so it is left to CI, which sets it explicitly.
npm --prefix "$FRONTEND" exec -- playwright install chromium

export TCP_WEB_URL="$BASE_URL"
# Only exported when resolved — an empty override would beat a spec's own
# code-level default (see ApiHelper.OIDC_DISCOVERY_URL, which this mirrors).
# Credential-needing specs skip themselves when these are absent; a missing
# token must not fail the rest of the suite.
[[ -n "$OIDC_URL" ]]      && export OIDC_DISCOVERY_URL="$OIDC_URL"
[[ -n "$CLIENT_ID" ]]     && export TEST_CLIENT_ID="$CLIENT_ID"
[[ -n "$CLIENT_SECRET" ]] && export TEST_CLIENT_SECRET="$CLIENT_SECRET"

npm --prefix "$REPO_ROOT" run test:browser -- ${PASSTHROUGH[@]+"${PASSTHROUGH[@]}"}
