#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<EOF
Usage: $(basename "$0") [-h|--help] [--base-url URL] [-- <jest options>]

Run the API endpoint test suite against a running LCP deployment.

Defaults to http://localhost:3000 when --base-url is not given, which is
where start-deployment.sh starts the stack. Start services first:

  ./scripts/start-deployment.sh --project tcp-api --env-file .env.testing
  $(basename "$0")                           # targets localhost:3000
  docker compose -p tcp-api --profile auth down -v

API tests verify authenticated HTTP requests against tcp-server using a real
Zitadel-issued JWT, obtained via the machine test user's client_credentials
grant. Its client secret is generated by Zitadel at bootstrap time (see
start-deployment.sh), so — unlike the old fixed test/test credentials —
there's no built-in default to fall back to. If --client-id/--client-secret
aren't given and TEST_CLIENT_ID/TEST_CLIENT_SECRET aren't already set, this
script reads them from the env file: --env-file if given, else .env.dev if
present, else .env.testing — checking its gitignored "<env-file>.local"
override first, since that's where start-deployment.sh writes the generated
values.

Any extra arguments after -- are passed through to Jest, for example:
  $(basename "$0") -- --testNamePattern="company"

Options:
  --base-url URL            tcp-server base URL (default: http://localhost:3000)
  --agent-url URL           tcp-agent URL (default: http://localhost:3001)
  --oidc-discovery-url URL  Full OIDC discovery URL
                            (default: http://localhost:8080/.well-known/openid-configuration)
  --client-id ID            Machine test user client ID (client_credentials)
  --client-secret SECRET    Machine test user client secret
  --env-file PATH           Env file to read TEST_CLIENT_ID/SECRET from when
                            not otherwise provided (default: .env.dev, else .env.testing)
  -h, --help                Show this help message and exit

Each option can also be supplied as an environment variable:
  LCP_SERVER_URL, LCP_AGENT_URL, OIDC_DISCOVERY_URL,
  TEST_CLIENT_ID, TEST_CLIENT_SECRET
CLI flags take precedence over environment variables, which take precedence
over the env file.
EOF
}

# Prevent inheriting stale values from a previous run's exports. Values are
# resolved from CLI flags or the env file — never from the parent shell.
unset LCP_SERVER_URL LCP_AGENT_URL OIDC_DISCOVERY_URL TEST_CLIENT_ID TEST_CLIENT_SECRET

BASE_URL="http://localhost:3000"
AGENT_URL=""
OIDC_URL=""
CLIENT_ID=""
CLIENT_SECRET=""
ENV_FILE=""
PASSTHROUGH=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-url)            BASE_URL="$2";         shift 2 ;;
    --agent-url)           AGENT_URL="$2";        shift 2 ;;
    --oidc-discovery-url)  OIDC_URL="$2";         shift 2 ;;
    --client-id)           CLIENT_ID="$2";        shift 2 ;;
    --client-secret)       CLIENT_SECRET="$2";    shift 2 ;;
    --env-file)            ENV_FILE="$2";         shift 2 ;;
    --) shift; PASSTHROUGH+=("$@"); break ;;
    -h|--help) usage; exit 0 ;;
    *) PASSTHROUGH+=("$1"); shift ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Resolve credentials from env file when not provided via CLI/env.
if [[ -z "$CLIENT_ID" || -z "$CLIENT_SECRET" ]]; then
  if [[ -z "$ENV_FILE" ]]; then
    if [[ -f "$REPO_ROOT/.env.dev" ]]; then
      ENV_FILE="$REPO_ROOT/.env.dev"
    else
      ENV_FILE="$REPO_ROOT/.env.testing"
    fi
  fi
  # TEST_CLIENT_ID/SECRET are generated by the Zitadel bootstrap, which writes
  # them to the gitignored "<env-file>.local" override (see start-deployment.sh),
  # not the committed base file. Prefer the override, fall back to the base file.
  for candidate in "$ENV_FILE.local" "$ENV_FILE"; do
    [[ -f "$candidate" ]] || continue
    [[ -n "$CLIENT_ID" ]]     || CLIENT_ID="$(grep -m1 '^TEST_CLIENT_ID=' "$candidate" | cut -d= -f2-)"
    [[ -n "$CLIENT_SECRET" ]] || CLIENT_SECRET="$(grep -m1 '^TEST_CLIENT_SECRET=' "$candidate" | cut -d= -f2-)"
  done
fi

# Write resolved values to a temp env file so Jest's globalSetup can pick
# them up without any shell-level exports.
ENV_RUN="$REPO_ROOT/.env.run"
trap 'rm -f "$ENV_RUN"' EXIT

{
  # Only write non-empty values — empty vars would overwrite code-level defaults
  # in helpers like ApiHelper.ts (which uses ?? '' for optional vars).
  [[ -n "$BASE_URL" ]]        && echo "LCP_SERVER_URL=$BASE_URL"
  [[ -n "$AGENT_URL" ]]       && echo "LCP_AGENT_URL=$AGENT_URL"
  [[ -n "$OIDC_URL" ]]        && echo "OIDC_DISCOVERY_URL=$OIDC_URL"
  [[ -n "$CLIENT_ID" ]]       && echo "TEST_CLIENT_ID=$CLIENT_ID"
  [[ -n "$CLIENT_SECRET" ]]   && echo "TEST_CLIENT_SECRET=$CLIENT_SECRET"
} > "$ENV_RUN"

npm --prefix "$REPO_ROOT" run test:api -- ${PASSTHROUGH[@]+"${PASSTHROUGH[@]}"}
