#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<EOF
Usage: $(basename "$0") [-h|--help] [--base-url URL] [-- <jest options>]

Run the API endpoint test suite against a running LCP deployment.

Defaults to http://localhost:3000 when --base-url is not given, which is
where start-deployment.sh starts the stack. Start services first:

  ./scripts/start-deployment.sh --project lcp-api --env-file .env.testing
  $(basename "$0")                           # targets localhost:3000
  docker compose -p lcp-api --profile auth down -v

API tests verify authenticated HTTP requests against lcp-server using a real
Zitadel-issued JWT, obtained via the machine test user's client_credentials
grant. Its client secret is generated by Zitadel at bootstrap time (see
start-deployment.sh), so — unlike the old fixed test/test credentials —
there's no built-in default to fall back to. If --client-id/--client-secret
aren't given and TEST_CLIENT_ID/TEST_CLIENT_SECRET aren't already exported,
this script reads them out of an env file: --env-file if given, else .env if
present, else .env.testing (the same file start-deployment.sh wrote them
into).

Any extra arguments after -- are passed through to Jest, for example:
  $(basename "$0") -- --testNamePattern="company"

Options:
  --base-url URL            lcp-server base URL (default: http://localhost:3000)
  --agent-url URL           lcp-agent URL (default: http://localhost:3001)
  --oidc-discovery-url URL  Full OIDC discovery URL
                            (default: http://localhost:8080/.well-known/openid-configuration)
  --client-id ID            Machine test user client ID (client_credentials)
  --client-secret SECRET    Machine test user client secret
  --env-file PATH           Env file to read TEST_CLIENT_ID/SECRET from when
                            not otherwise provided (default: .env, else .env.testing)
  -h, --help                Show this help message and exit

Each option can also be supplied as an environment variable:
  LCP_SERVER_URL, LCP_AGENT_URL, OIDC_DISCOVERY_URL,
  TEST_CLIENT_ID, TEST_CLIENT_SECRET
CLI flags take precedence over environment variables, which take precedence
over the env file.
EOF
}

BASE_URL="${LCP_SERVER_URL:-http://localhost:3000}"
LCP_AGENT_URL="${LCP_AGENT_URL:-}"
OIDC_DISCOVERY_URL="${OIDC_DISCOVERY_URL:-}"
TEST_CLIENT_ID="${TEST_CLIENT_ID:-}"
TEST_CLIENT_SECRET="${TEST_CLIENT_SECRET:-}"
ENV_FILE=""
PASSTHROUGH=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-url)            BASE_URL="$2";            shift 2 ;;
    --agent-url)           LCP_AGENT_URL="$2";       shift 2 ;;
    --oidc-discovery-url)  OIDC_DISCOVERY_URL="$2";  shift 2 ;;
    --client-id)           TEST_CLIENT_ID="$2";      shift 2 ;;
    --client-secret)       TEST_CLIENT_SECRET="$2";  shift 2 ;;
    --env-file)            ENV_FILE="$2";            shift 2 ;;
    --) shift; PASSTHROUGH+=("$@"); break ;;
    -h|--help) usage; exit 0 ;;
    *) PASSTHROUGH+=("$1"); shift ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Fall back to reading the machine test user's credentials out of the env
# file start-deployment.sh bootstrapped them into, mirroring the .env / else
# .env.testing precedence start-dev.sh and lcp-cli.sh already use.
if [[ -z "$TEST_CLIENT_ID" || -z "$TEST_CLIENT_SECRET" ]]; then
  if [[ -z "$ENV_FILE" ]]; then
    if [[ -f "$REPO_ROOT/.env" ]]; then
      ENV_FILE="$REPO_ROOT/.env"
    else
      ENV_FILE="$REPO_ROOT/.env.testing"
    fi
  fi
  if [[ -f "$ENV_FILE" ]]; then
    [[ -n "$TEST_CLIENT_ID" ]] || TEST_CLIENT_ID="$(grep -m1 '^TEST_CLIENT_ID=' "$ENV_FILE" | cut -d= -f2-)"
    [[ -n "$TEST_CLIENT_SECRET" ]] || TEST_CLIENT_SECRET="$(grep -m1 '^TEST_CLIENT_SECRET=' "$ENV_FILE" | cut -d= -f2-)"
  fi
fi

export LCP_SERVER_URL="$BASE_URL"
[[ -n "$LCP_AGENT_URL" ]]       && export LCP_AGENT_URL
[[ -n "$OIDC_DISCOVERY_URL" ]]  && export OIDC_DISCOVERY_URL
[[ -n "$TEST_CLIENT_ID" ]]      && export TEST_CLIENT_ID
[[ -n "$TEST_CLIENT_SECRET" ]]  && export TEST_CLIENT_SECRET

npm --prefix "$REPO_ROOT" run test:api -- ${PASSTHROUGH[@]+"${PASSTHROUGH[@]}"}
