import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Creates the `knowledge_chunk` table and adds the pgvector `embedding` column.
 *
 * TypeORM generates the base table structure from the {@link KnowledgeChunk} entity.
 * The `embedding vector(1536)` column is added by hand because TypeORM does not
 * generate pgvector DDL. Dimension 1536 matches OpenAI `text-embedding-3-small`
 * and LM Studio `nomic-embed-text`. A different embedding model requires a
 * new migration to re-create the column with the correct dimension and
 * re-embed all existing chunks.
 *
 * The IVFFlat index (cosine distance) enables efficient approximate nearest-neighbour
 * search. `lists = 100` is a reasonable default for up to ~1M vectors per company.
 */
export class AddKnowledgeChunk1782246974122 implements MigrationInterface {
  name = 'AddKnowledgeChunk1782246974122';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "knowledge_chunk" (
        "id"           uuid              NOT NULL DEFAULT uuid_generate_v4(),
        "companyId"    uuid              NOT NULL,
        "roleId"       uuid              NOT NULL,
        "documentPath" text              NOT NULL,
        "chunkIndex"   integer           NOT NULL,
        "content"      text              NOT NULL,
        "createdAt"    TIMESTAMP         NOT NULL DEFAULT now(),
        CONSTRAINT "PK_knowledge_chunk" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_knowledge_chunk_company_role" ON "knowledge_chunk" ("companyId", "roleId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_knowledge_chunk_role_document" ON "knowledge_chunk" ("roleId", "documentPath")`,
    );
    // pgvector column — not generated by TypeORM
    await queryRunner.query(
      `ALTER TABLE "knowledge_chunk" ADD COLUMN embedding vector(1536)`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_knowledge_chunk_embedding" ON "knowledge_chunk" USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_knowledge_chunk_embedding"`,
    );
    await queryRunner.query(`DROP TABLE "knowledge_chunk"`);
  }
}
