import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Creates the `episodic_memory` table and adds the pgvector `embedding` column.
 *
 * Follows the same pattern as {@link AddKnowledgeChunk1782246974122}: the
 * `embedding vector(1536)` column is added via raw SQL because TypeORM does not
 * generate pgvector DDL.
 */
export class AddEpisodicMemory1782247100000 implements MigrationInterface {
  name = 'AddEpisodicMemory1782247100000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "episodic_memory" (
        "id"        uuid      NOT NULL DEFAULT uuid_generate_v4(),
        "companyId" uuid      NOT NULL,
        "roleId"    uuid      NOT NULL,
        "agentId"   uuid,
        "content"   text      NOT NULL,
        "tags"      jsonb,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "PK_episodic_memory" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_episodic_memory_company_role" ON "episodic_memory" ("companyId", "roleId")`,
    );
    // pgvector column — not generated by TypeORM
    await queryRunner.query(
      `ALTER TABLE "episodic_memory" ADD COLUMN embedding vector(1536)`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_episodic_memory_embedding" ON "episodic_memory" USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_episodic_memory_embedding"`,
    );
    await queryRunner.query(`DROP TABLE "episodic_memory"`);
  }
}
